package com.fulfilment.application.monolith.exceptions;

public enum ErrorCode {
    BODY_MISSING,
    FIELD_IS_REQUIRED,
    WAREHOUSE_ALREADY_ARCHIVED,
    WAREHOUSE_ALREADY_EXIST,
    WAREHOUSE_NOT_FOUND,
    WAREHOUSE_CAPACITY_NOT_ENOUGH,
    MAX_WAREHOUSE_NUMBER_REACHED,
    WAREHOUSE_STOCK_MISMATCH,
    WAREHOUSE_LOCATION_EXCEEDED_MAX_CAPACTY,
    BUSINESS_UNIT_CODE_NOT_MATCH,

    FULFILLMENT_ALREADY_EXIST,
    PRODUCT_FULFILMENT_MAX_WAREHOUSES_PER_STORE_EXCEEDED,
    STORE_FULFILMENT_MAX_WAREHOUSES_EXCEEDED,
    WAREHOUSE_MAX_PRODUCT_TYPES_EXCEEDED
}
