package com.fulfilment.application.monolith.exceptions;

public enum ErrorCode {
    BODY_MISSING,
    FIELD_IS_REQUIRED,
    WAREHOUSE_ALREADY_ARCHIVED,
    WAREHOUSE_ALREADY_EXIST,
    WAREHOUSE_NOT_FOUND,
    WAREHOUSE_CAPACITY_NOT_ENOUGH,
    MAX_WAREHOUSE_NUMBER_REACHED,
    WAREHOUSE_STOCK_MISMATCH,
    WAREHOUSE_LOCATION_EXCEEDED_MAX_CAPACTY
}
